### ISSUE TITLE
[Suggestion] Dynamic Trees compatibility.

### ISSUE THREAD

**Issue by 63502** [Lemonszz/Corvus#1]
It would be a nice touch to have the frankincense tree fit in with other dynamic trees.
![2018-11-22_01 31 12](https://user-images.githubusercontent.com/15267053/48886290-6e6bd380-edf9-11e8-93ad-1134017d90e8.png)

**Comment by Lemonszz** [comment]
While that would be nice, it's out of scope for what we want to do right now. Maybe in the future.
