### ISSUE TITLE
Not identifying when a puppy is killed

### ISSUE THREAD

**Issue by dimmybug** [Lemonszz/Corvus#8]
Please fill out this template when submitting an issue.

---
**Mod Version**:  1.2.3

**Forge Version**: 14.23.5.2846

**This issue occurs on the lastest version of Forge? (Y/N)**: Yes

**Crash Log (Post to Pastebin/Other Text hosting)**:  N/A

**What happens**: Even after killing multiple wolf puppies, it doesn't recognise that I've done so. Not in the Advancements, nor in the Grimoire, and nothing is unlocked. I'm not sure if I'm doing something wrong or if I should be doing a ritual of sorts, but it just isn't working.

**Comment by Lemonszz** [comment]
As long as you've done the awaken ritual, it should unlock.

It might mess up if you're using a modpack that removes/disables Corvus' advancements (That'll be fixed in the next version)

**Comment by dimmybug** [comment]
Okay, thanks, it's probably the other mods then :)
